### ISSUE TITLE
Toast

### ISSUE THREAD

**Issue by I-am-abdulazeez** [inkline/inkline#211]
* **I'm submitting a:**
    - [x] Feature Request 
  
* **Toast request**
    A toast that can be called after some actions

* **[Something Like this](https://vue.chakra-ui.com/toast)**

**Comment by alexgrozav** [comment]
Closing as duplicate of https://github.com/inkline/inkline/issues/162. 

The Chakra UI example looks like a good starting point. I'd say we should use a custom implementation since `breadstick` relies on `animejs`. The animations can be easily handled using CSS transitions. 

@masihtak will start working on it.
