### ISSUE TITLE
Treeshaking on Nuxt3

### ISSUE THREAD

**Issue by tasiotas** [inkline/inkline#280]
Hi,

I followed instructions to install Inkline on Nuxt3.

Seems like treeshaking isn't working. All components are included both in dev and build.

I started Discussion thread about it, but later realized its more of an Issue.
Thank you

**Comment by alexgrozav** [comment]
Hi @tasiotas, the code behind the `nuxt-module-inkline` is pretty standard and has been reviewed by @pi0 from the nuxt team as well. Perhaps he can shed some light on what's happening? Is this caused by the `global: true` setting?

https://github.com/inkline/nuxt-module-inkline/blob/main/src/module.ts

**Comment by Tragio** [comment]
@alexgrozav this seems related to this https://github.com/oruga-ui/oruga/issues/298

**Comment by tasiotas** [comment]
> Could this be caused by the `global: true` setting?

Can I override it somehow?

Is anyone able to use Inkline with Nuxt?

**Comment by tasiotas** [comment]
sorry about closing/opening, it was mistake

I commented ```global: true``` in node_modules folder, and it worked fine. Now I only get necessary css files.

**Comment by alexgrozav** [comment]
Thanks a lot for the update! I've disabled `global` option in the new 3.1.1 release.
