### ISSUE TITLE
Clicking on the arrow in a "select" component does nothing

### ISSUE THREAD

**Issue by mtancoigne** [inkline/inkline#285]
* **What is the expected and current behavior?**
  On a "select" component, I expect the dropdown list to show when I click on the little arrow of the component

* **Steps to reproduce**
  1. Visit https://inkline.io/docs/forms/select
  2. Click on the arrow on the demo "select"
  3. Nothing happens

* **Please tell us about your environment:**
    - Version: v3.0.8, at least
    - Browser: Firefox 96.0 (64-bit)
    - Language: At least ES (tested locally), and whatever the demo uses

* **Other information**
   None of interest

**Comment by scott-t** [comment]
It goes one step further for me. I've got the button causing my form to be submitted. I assume something to do with being rendered as a <button>.

**Comment by scott-t** [comment]
Playing around to fix my issue with the form being submitted, it seems likely https://github.com/inkline/inkline/blob/9deb0598c067ed74fbb957c77d613bf8238cec78/src/components/ISelect/template.html#L43 needs to be @click.prevent rather than simply @click. Not sure if that'll fix the non-functional dropdown entirely or not though.

**Comment by mtancoigne** [comment]
and `role="button"` too...

**Comment by alexgrozav** [comment]
Fixed in #289. Thank you for reporting the issue! :)
