### ISSUE TITLE
ISelect stores the id of the selected option instead of the option itself

### ISSUE THREAD

**Issue by GiovaniAtBasf** [inkline/inkline#380]
* **What is the expected and current behavior?**
 ISelect should store the selected **option** (not just the idField) in the modelValue, instead it currently stores the idField. This change makes it so I have to search for the option again to get the entire object. At the very least there needs to be an option to get the entire option stored. This used to work like this in v3. 

The official inkline documentation also mentions:
> The selected value will be the option itself

* **Steps to reproduce**
  Take the example from the [official documentation](https://www.inkline.io/docs/forms/select) and you'll see it does what I described. I have provided a stackblitz for your convenience.

* **Please tell us about your environment:**
    - Version: >=4.0.0
    - Browser: all
    - Language: all

* **Other information**
  [Stackblitz](https://stackblitz.com/edit/inkline-ukw1bp?file=src%2FApp.vue)

**Comment by alexgrozav** [comment]
This is now the intended behaviour. 

As an attempt to simplify and unify the way all the form components with options work, the selected value field is now always the `id` field. It is used as the value being selected because it's the only required value in form options array, and it's also used as part of the required rendering key.

I'm sorry for the inconvenience. I do hope the choice behind it will have a positive impact on your workflow, though.
