### ISSUE TITLE
Change Number Input behavior

### ISSUE THREAD

**Issue by alexgrozav** [inkline/inkline#45]
This is open for discussion. 

**Scenario**: writing 55 into an input with a maximum value of 10 will change the value to 10.

**Current behavior**
Right now, writing a number larger than the `max` specified value will resolve to the maximum value. Writing 55 will change the value to 10.

**Possible behavior**
We could ignore inputting the second 5 and leave the value as 5 instead of changing to 10.

Is the current behavior good from an User Experience point of view?

**Comment by krajcovic46** [comment]
Hello,

the possible behaviour (ignoring the next input digit if it makes the current number bigger than the `max`) is the least ideal of them all simply because it's confusing -- if a form field is active, there is no reason to ignore the input. If a person makes an action, they expect a reaction. Because of this, having some kind of feedback for the user is a must. Even if an error message saying that the provided input is higher than a possible `max` is displayed, the user has to then delete the current value they inserted and reenter it.

The current solution is satisfactory for an experienced user which understands that the form field is ceiled and they input a number which is too high. For an inexperienced user, this might be problematic. They might not understand that they provided a number which is higher than some arbitrary `max` value. In short, changing the value automatically might be time-saving and convenient for an "experienced" user but confusing for an inexperienced one.

From my point of view, the ideal solution would be allowing users to write an arbitrary value into the field. If the input value is higher than the `max`, an error would be shown, saying that the provided value is too high and displaying the `max` value.

Let me know what you think.

**Comment by alexgrozav** [comment]
I agree that changing the users input is not the right way to go here.

The error state you're mentioning can be easily done through Inkline's Form Validation and it's probably best that we don't interfere with that. 

The max and min are optional and should influence the actual input of the user.

Question is, which one would be more intuitive? We'll need to look at other ui frameworks (or maybe the native number input) and see what worked for them.

**Comment by mtancoigne** [comment]
Firefox handles the max value when the form is submitted, the same way `required` fields are handled: a message is shown when the input don't fit.

I think it's best to stick to browser behaviors when we can. If the dev uses a validation mechanism (the one provided by Inkline or another), then a message can be shown stating that the value is incorrect. If he doesn't, the browser handles it.

That way, users are happy with a known behavior, and devs are happy with flexibility.

**Comment by alexgrozav** [comment]
> Firefox handles the max value when the form is submitted, the same way `required` fields are handled: a message is shown when the input don't fit.
> 
> I think it's best to stick to browser behaviors when we can. If the dev uses a validation mechanism (the one provided by Inkline or another), then a message can be shown stating that the value is incorrect. If he doesn't, the browser handles it.
> 
> That way, users are happy with a known behavior, and devs are happy with flexibility.

Perhaps it's best if we just remove the `max` and `min` implementation from the `i-number-input` and leave it to the validation setup?

**Comment by mtancoigne** [comment]
Yes, we should keep the props and remove the current behavior when input is changed.
