### ISSUE TITLE
Manually call form validation

### ISSUE THREAD

**Issue by mtancoigne** [inkline/inkline#53]
* **I'm submitting a:**

  - [ ] Bug Report
  - [x] Feature Request
  
* **What is the current behavior?**

Form validation is only on `blur` and `input` events.

* **What is the expected behavior?** (If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** viahttps://plnkr.co or similar.)

I'd like to validate manually when I decide to with something like `this.$form.validate(this.inputs)`. To be really great, the `validate()` method should return a promise, to allow custom validators to execute (i.e.: remote validation).

**Comment by alexgrozav** [comment]
You can use `this.schema.validate()` to manually validate the schema. 

I know it's not documented and perhaps it should be. Each schema group and schema object has a `validate()` method which you can call to have it validate the schema tree (if you call, let's say `this.schema.address.city.validate()`, it will validate all of it's ancestors as well: `this.schema.address` and `this.schema` itself).

The method does not return a promise because all validation is done in place and doesn't need to be asynchronous. You could do something like:
~~~js
this.schema.validate();

if (this.schema.valid) {
    // do something
}
~~~

**Comment by alexgrozav** [comment]
You can use `this.schema.validate()` to manually validate the schema. 

I know it's not documented and perhaps it should be. Each schema group and schema object has a `validate()` method which you can call to have it validate the schema tree (if you call, let's say `this.schema.address.city.validate()`, it will validate all of it's ancestors as well: `this.schema.address` and `this.schema` itself).

The method does not return a promise because all validation is done in place and doesn't need to be asynchronous. You could do something like:
~~~js
this.schema.validate();

if (this.schema.valid) {
    // do something
}
~~~

**Comment by alexgrozav** [comment]
You can use `this.schema.validate()` to manually validate the schema. 

I know it's not documented and perhaps it should be. Each schema group and schema object has a `validate()` method which you can call to have it validate the schema tree (if you call, let's say `this.schema.address.city.validate()`, it will validate all of it's ancestors as well: `this.schema.address` and `this.schema` itself).

The method does not return a promise because all validation is done in place and doesn't need to be asynchronous. You could do something like:
~~~js
this.schema.validate();

if (this.schema.valid) {
    // do something
}
~~~

**Comment by mtancoigne** [comment]
That's totally what I was looking for :)

I guess I had a bad schema when I tried!
